version: "3.8"

services:
  db:
    image: ankane/pgvector # includes Postgres + pgvector
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5445:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
