version: "3.8"

services:
  db:
    image: ankane/pgvector
    container_name: pgvector-db-carleton-cs-bot
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5445:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-carleton-cs-bot
    restart: unless-stopped
    ports:
      - "6370:6379"

  # bot:
  #   build: .
  #   container_name: carleton-cs-bot
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: sh -c "python app/ingest.py && python app/main.py"
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #     DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase

volumes:
  pg_data:
