"""add sources

Revision ID: 6c927b2aeba5
Revises: 781a41a2f89f
Create Date: 2025-04-24 22:18:05.238593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c927b2aeba5"
down_revision: Union[str, None] = "781a41a2f89f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("webpage", "file", name="source_type"), nullable=False
        ),
        sa.Column("reference", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.add_column("chunks", sa.Column("source_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "chunks", "sources", ["source_id"], ["id"])
    op.drop_column("chunks", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "chunks", type_="foreignkey")
    op.drop_column("chunks", "source_id")
    op.drop_table("sources")
    # ### end Alembic commands ###
